language: php

install:
    - composer install

# phpunit is run by default, skip it
script: skip

jobs:
    include:
        -
            stage: test
            php: 7.2
            name: Run
            script:
                - bin/ci

        -
            stage: test
            php: 7.2
            name: "Coding Standards"
            script:
                - composer check-cs

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email:
        on_success: never
